---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: image-processor-api
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: image-processor-api
spec:
  params:
    - name: clusterBuilder
      value: full
  env:
    - name: MLFLOW_TRACKING_URI
      value: http://mlflow.${DATA_E2E_BASE_URL}
    - name: DATA_E2E_MLAPP_GIT_REPO
      value: ${DATA_E2E_MLAPP_GIT_REPO}
    - name: DATA_E2E_MLAPP_GIT_REPO_BRANCH
      value: ${DATA_E2E_MLAPP_GIT_REPO_BRANCH}
    - name: DATA_E2E_MLAPP_INFERENCE_DB_SCHEMA
      value: ${DATA_E2E_MLAPP_INFERENCE_DB_SCHEMA}
  source:
    git:
      url: https://github.com/agapebondservant/ml-image-processing-app.git
      ref:
        branch: main