---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: image-processor-kfpmain
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: image-processor-kfpmain
spec:
  #image: index.docker.io/oawofolu/image-processor-default@sha256:ba3df083e2abf17117488d918ba2321ec7ba9999981077416725cb3f34b09c6e
  params:
    - name: clusterBuilder
      value: full
    #- name: api_descriptor
    #  value:
    #    type: openapi
    #    location:
    #      path: "/v3/api-docs"
    #    description: "A set of API endpoints for the ML Image Processing Demo App."
  env:
    - name: MLFLOW_TRACKING_URI
      value: http://mlflow.${DATA_E2E_BASE_URL}
  source:
    git:
      url: https://github.com/agapebondservant/ml-image-processing-app.git
      ref:
        branch: kfp-main