---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: image-processor
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: image-processor
spec:
  image: index.docker.io/oawofolu/image-processor-default@sha256:d87af66e315153ecd30dd158f24d6d47bca11aa45db79dbca4507a9b28116580
  params:
    - name: clusterBuilder
      value: base
  source:
    git:
      url: https://github.com/agapebondservant/ml-image-processing-app.git
      ref:
        branch: main