apiVersion: batch/v1
kind: Job
metadata:
  name: submit-workflow
  annotations:
    kapp.k14s.io/update-strategy: always-replace
spec:
  template:
    spec:
      containers:
        - name: submit-workflow
          image: argoproj/argocli
          args: ["resubmit ml-image-processing-workflow-mri --log  2>/dev/null || true"]
      restartPolicy: Never
  backoffLimit: 0