apiVersion: batch/v1
kind: Job
metadata:
  name: submit-workflow
  annotations:
    kapp.k14s.io/update-strategy: always-replace
spec:
  template:
    spec:
      containers:
        - name: submit-workflow
          image: argoproj/argocli
          args: ["resubmit", "--log", "ml-image-processing-workflow-mri"]
      restartPolicy: Never
  backoffLimit: 0
  podFailurePolicy:
    rules:
      - action: Ignore
        onExitCodes:
          operator: NotIn
          values: [ 4200000 ]