apiVersion: batch/v1
kind: Job
metadata:
  name: resubmit-workflow
  annotations:
    kapp.k14s.io/update-strategy: always-replace
    kapp.k14s.io/change-group: "apps.big.co/argo-pipeline-job"
    kapp.k14s.io/change-rule: "upsert before upserting apps.big.co/argo-pipelines"
spec:
  template:
    spec:
      containers:
        - name: resubmit-workflow
          image: oawofolu/argocli:latest
          command: [/bin/sh]
          args: ["-c", "argo resubmit --log ml-image-processing-workflow-mri || true"]
      restartPolicy: Never
  backoffLimit: 0
  podFailurePolicy:
    rules:
      - action: Ignore
        onExitCodes:
          operator: NotIn
          values: [ 4200000 ]