#@ load("@ytt:data", "data")
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: ml-image-processing-pipeline-app-mri
spec:
  serviceAccountName: default
  fetch:
    - git:
        url: https://github.com/agapebondservant/ml-image-processing-app
        ref: origin/mainmri
    - http:
        url: https://api.github.com/repos/agapebondservant/ml-image-processing-app/commits/mainmri

  template:
    - ytt:
        paths:
          - 0/config/mri/job.yaml
          - 0/config/mri/pipeline.yaml
          - 0/config/mri/values.yaml
          - #@ "1/" + data.values.environment_name

  deploy:
    - kapp: {}