#@ load("@ytt:data", "data")
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: ml-image-processing-pipeline-app-a
spec:
  serviceAccountName: default
  fetch:
    - git:
        url: #@ "https://github.com/{}/{}".format(data.values.git_repo_user,data.values.git_repo_app)
        ref: #@ "origin/{}".format(data.values.environment_name)

  template:
    - ytt:
        paths:
          - config/cifar/job.yaml
          - config/cifar/pipeline.yaml
          - config/cifar/values.yaml
          - kapp-marker

  deploy:
    - kapp: {}