#@ load("@ytt:data", "data")
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: ml-image-processing-pipeline-app-a
spec:
  serviceAccountName: default
  fetch:
    - git:
        url: #@ "https://github.com/" + data.values.git_repo_user + "/" + data.values.git_repo_app
        ref: #@ "origin/" + data.values.environment_name
    - http:
        url: #@ "https://api.github.com/repos/" + data.values.git_repo_user + "/" + data.values.git_repo_app + "/commits/" + data.values.environment_name

  template:
    - ytt:
        paths:
          - 0/config/cifar/job.yaml
          - 0/config/cifar/pipeline.yaml
          - 0/config/cifar/values.yaml
          - #@ "1/" + data.values.environment_name

  deploy:
    - kapp: {}